create or replace TABLE AIRBNB.DEV."dbtlogs" (
	TARGETSCHEMA VARCHAR(50),
	MODELNAME VARCHAR(50),
	MATERIALIZATION VARCHAR(50),
	JOBSTARTDATE TIMESTAMP_TZ(6),
	MODELCREATESTARTDATE TIMESTAMP_TZ(6),
	MODELCREATEENDDATE TIMESTAMP_TZ(6),
	STATUS VARCHAR(50),
	EXECUTIONTIME VARCHAR(500),
	INVOCATIONID VARCHAR(50),
	DBTVERSION VARCHAR(50),
	RECORDINSERTEDDATE TIMESTAMP_TZ(6),
	ROWCOUNT VARCHAR(20)
);